name: Telegram Notification

on:
  push:
    branches:
      - main # Замените на имя вашей основной ветки

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.3.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "New push to the repository: ${{ github.repository }}"
